### ISSUE TITLE
Don't exists TestbenchWindow in this Projects?

### ISSUE THREAD

**Issue by 506015172** [PeterHuberSg/WpfControlTestbench#1]
When I try to run XYGraph project,used this project,  no exists TestbenchWindow in this Projects?

**Comment by PeterHuberSg** [comment]
I guess you are using https://github.com/PeterHuberSg/XYGraphLib ? I wrote that many years ago and I don't remember if it links to PeterHuberSg/WpfControlTestbench.

When I "published" (writing Readme here and an article on CodeProject) WpfControlTestbench, I changed it quite a lot, removed many dependencies. If XYGraphLib  is using it, they no longer match. 

The control with the chart is in PeterHuberSg/XYGraphLib/blob/master/XYGraphLib/Chart1Plot1X1YLegend.cs. You can try to Build just XYGraphLib/XYGraphLib, which should not have any dependency on TestbenchWindow . 

However, you might run into other dependency problems. 

XYGraphLib I haven't "published" yet, it is still work in progress. I might update it in the next 2-3 months.

**Comment by 506015172** [comment]
Thank you! I will try it again。
